<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Login</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<a href=""><?php echo $_SESSION['user']  ?></a>
<a href="/logout">Logout</a>
<div class="container">
    <div>
        <h1>Welcome to Dashboard</h1>
    </div>
</div>
</body>
</html>
