<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Login</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<div class="container">
    <div class="form">
        <form action="/register" method="post">
            <input type="name" name="name" placeholder="Name" required/>
            <input type="email" name="email" placeholder="Email" required/>
            <input type="password" name="password" placeholder="Password" required/>
            <input type="hidden" name="token" value="<?php echo $token ?>"/>
            <button type="submit"/>Register</button>
        </form>
        <?php
        if(isset($status) && $status == "0"){
            echo "Email already exists. Choose another email.";
        }
        ?>
        <a href="/login">Login</a>
        <br>


    </div>
</div>
</body>
</html>
